/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetImageBingDailyHistory200Response {
    #[serde(rename = "resolution", skip_serializing_if = "Option::is_none")]
    pub resolution: Option<String>,
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::GetImageBingDailyHistory200ResponseItemsInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::GetImageBingDailyHistory200ResponsePagination>>,
}

impl GetImageBingDailyHistory200Response {
    pub fn new() -> GetImageBingDailyHistory200Response {
        GetImageBingDailyHistory200Response {
            resolution: None,
            items: None,
            pagination: None,
        }
    }
}

