/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscTrackingCarriers200Response {
    /// 快递公司列表
    #[serde(rename = "carriers", skip_serializing_if = "Option::is_none")]
    pub carriers: Option<Vec<models::GetMiscTrackingCarriers200ResponseCarriersInner>>,
    /// 支持的快递公司总数
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl GetMiscTrackingCarriers200Response {
    pub fn new() -> GetMiscTrackingCarriers200Response {
        GetMiscTrackingCarriers200Response {
            carriers: None,
            total: None,
        }
    }
}

