/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSocialBilibiliUserinfo200Response {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::GetSocialBilibiliUserinfo200ResponseData>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl GetSocialBilibiliUserinfo200Response {
    pub fn new() -> GetSocialBilibiliUserinfo200Response {
        GetSocialBilibiliUserinfo200Response {
            code: None,
            data: None,
            message: None,
        }
    }
}

