/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAiTranslateLanguages200ResponseData {
    #[serde(rename = "languages", skip_serializing_if = "Option::is_none")]
    pub languages: Option<Vec<models::GetAiTranslateLanguages200ResponseDataLanguagesInner>>,
    #[serde(rename = "styles", skip_serializing_if = "Option::is_none")]
    pub styles: Option<Vec<models::GetAiTranslateLanguages200ResponseDataStylesInner>>,
    #[serde(rename = "contexts", skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<models::GetAiTranslateLanguages200ResponseDataContextsInner>>,
}

impl GetAiTranslateLanguages200ResponseData {
    pub fn new() -> GetAiTranslateLanguages200ResponseData {
        GetAiTranslateLanguages200ResponseData {
            languages: None,
            styles: None,
            contexts: None,
        }
    }
}

