/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGameMinecraftHistoryid200Response {
    /// 状态码，200代表成功。
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    /// 一个包含所有历史用户名的数组，按时间倒序排列。
    #[serde(rename = "history", skip_serializing_if = "Option::is_none")]
    pub history: Option<Vec<models::GetGameMinecraftHistoryid200ResponseHistoryInner>>,
    /// 玩家当前的用户名。
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// 历史名称的总数（包含当前名称）。
    #[serde(rename = "name_num", skip_serializing_if = "Option::is_none")]
    pub name_num: Option<i32>,
    /// 被查询玩家的32位无破折号UUID。
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

impl GetGameMinecraftHistoryid200Response {
    pub fn new() -> GetGameMinecraftHistoryid200Response {
        GetGameMinecraftHistoryid200Response {
            code: None,
            history: None,
            id: None,
            name_num: None,
            uuid: None,
        }
    }
}

