/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSocialBilibiliReplies200ResponseRepliesInnerMemberLevelInfo {
    /// 用户的B站等级。
    #[serde(rename = "current_level", skip_serializing_if = "Option::is_none")]
    pub current_level: Option<f64>,
}

impl GetSocialBilibiliReplies200ResponseRepliesInnerMemberLevelInfo {
    pub fn new() -> GetSocialBilibiliReplies200ResponseRepliesInnerMemberLevelInfo {
        GetSocialBilibiliReplies200ResponseRepliesInnerMemberLevelInfo {
            current_level: None,
        }
    }
}

