/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGithubUser200ResponseActivityTimelineInner {
    /// 月份，格式为 YYYY-MM。
    #[serde(rename = "month", skip_serializing_if = "Option::is_none")]
    pub month: Option<String>,
    /// 该月的贡献总数。
    #[serde(rename = "contribution_count", skip_serializing_if = "Option::is_none")]
    pub contribution_count: Option<i32>,
}

impl GetGithubUser200ResponseActivityTimelineInner {
    pub fn new() -> GetGithubUser200ResponseActivityTimelineInner {
        GetGithubUser200ResponseActivityTimelineInner {
            month: None,
            contribution_count: None,
        }
    }
}

