/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSocialBilibiliLiveroom200ResponseNewPendants : 主播佩戴信息。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSocialBilibiliLiveroom200ResponseNewPendants {
    #[serde(rename = "frame", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub frame: Option<Option<Box<models::GetSocialBilibiliLiveroom200ResponseNewPendantsFrame>>>,
    #[serde(rename = "badge", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub badge: Option<Option<Box<models::GetSocialBilibiliLiveroom200ResponseNewPendantsBadge>>>,
}

impl GetSocialBilibiliLiveroom200ResponseNewPendants {
    /// 主播佩戴信息。
    pub fn new() -> GetSocialBilibiliLiveroom200ResponseNewPendants {
        GetSocialBilibiliLiveroom200ResponseNewPendants {
            frame: None,
            badge: None,
        }
    }
}

