/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMs {
    #[serde(rename = "fast_mode", skip_serializing_if = "Option::is_none")]
    pub fast_mode: Option<i32>,
    #[serde(rename = "normal_mode", skip_serializing_if = "Option::is_none")]
    pub normal_mode: Option<i32>,
}

impl GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMs {
    pub fn new() -> GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMs {
        GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMs {
            fast_mode: None,
            normal_mode: None,
        }
    }
}

