/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscHolidayCalendar200ResponseData {
    /// 查询模式：day、month、year。
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Box<models::GetMiscHolidayCalendar200ResponseDataQuery>>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Box<models::GetMiscHolidayCalendar200ResponseDataSummary>>,
    /// 日期明细列表。
    #[serde(rename = "days", skip_serializing_if = "Option::is_none")]
    pub days: Option<Vec<models::GetMiscHolidayCalendar200ResponseDataDaysInner>>,
    /// 节日事件列表。
    #[serde(rename = "holidays", skip_serializing_if = "Option::is_none")]
    pub holidays: Option<Vec<models::GetMiscHolidayCalendar200ResponseDataHolidaysInner>>,
    #[serde(rename = "nearby", skip_serializing_if = "Option::is_none")]
    pub nearby: Option<Box<models::GetMiscHolidayCalendar200ResponseDataNearby>>,
}

impl GetMiscHolidayCalendar200ResponseData {
    pub fn new() -> GetMiscHolidayCalendar200ResponseData {
        GetMiscHolidayCalendar200ResponseData {
            mode: None,
            query: None,
            summary: None,
            days: None,
            holidays: None,
            nearby: None,
        }
    }
}

