/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGithubUser200ResponseActivityContributionCalendarWeeksInner {
    /// 这一周的第一天日期。
    #[serde(rename = "first_day", skip_serializing_if = "Option::is_none")]
    pub first_day: Option<String>,
    /// 这一周中每天的贡献明细。
    #[serde(rename = "contribution_days", skip_serializing_if = "Option::is_none")]
    pub contribution_days: Option<Vec<models::GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner>>,
}

impl GetGithubUser200ResponseActivityContributionCalendarWeeksInner {
    pub fn new() -> GetGithubUser200ResponseActivityContributionCalendarWeeksInner {
        GetGithubUser200ResponseActivityContributionCalendarWeeksInner {
            first_day: None,
            contribution_days: None,
        }
    }
}

