/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscWorldtime200Response {
    #[serde(rename = "datetime", skip_serializing_if = "Option::is_none")]
    pub datetime: Option<String>,
    #[serde(rename = "offset_seconds", skip_serializing_if = "Option::is_none")]
    pub offset_seconds: Option<i32>,
    #[serde(rename = "offset_string", skip_serializing_if = "Option::is_none")]
    pub offset_string: Option<String>,
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(rename = "timestamp_unix", skip_serializing_if = "Option::is_none")]
    pub timestamp_unix: Option<i32>,
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    #[serde(rename = "weekday", skip_serializing_if = "Option::is_none")]
    pub weekday: Option<String>,
}

impl GetMiscWorldtime200Response {
    pub fn new() -> GetMiscWorldtime200Response {
        GetMiscWorldtime200Response {
            datetime: None,
            offset_seconds: None,
            offset_string: None,
            query: None,
            timestamp_unix: None,
            timezone: None,
            weekday: None,
        }
    }
}

