/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSocialBilibiliReplies200ResponseRepliesInnerMember : 发表评论的用户信息。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSocialBilibiliReplies200ResponseRepliesInnerMember {
    /// 用户昵称。
    #[serde(rename = "uname", skip_serializing_if = "Option::is_none")]
    pub uname: Option<String>,
    /// 用户性别。
    #[serde(rename = "sex", skip_serializing_if = "Option::is_none")]
    pub sex: Option<String>,
    /// 用户头像的URL。
    #[serde(rename = "avatar", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
    #[serde(rename = "level_info", skip_serializing_if = "Option::is_none")]
    pub level_info: Option<Box<models::GetSocialBilibiliReplies200ResponseRepliesInnerMemberLevelInfo>>,
}

impl GetSocialBilibiliReplies200ResponseRepliesInnerMember {
    /// 发表评论的用户信息。
    pub fn new() -> GetSocialBilibiliReplies200ResponseRepliesInnerMember {
        GetSocialBilibiliReplies200ResponseRepliesInnerMember {
            uname: None,
            sex: None,
            avatar: None,
            level_info: None,
        }
    }
}

