/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSocialBilibiliVideoinfo200ResponseDescV2Inner {
    /// 简介文本。
    #[serde(rename = "raw_text", skip_serializing_if = "Option::is_none")]
    pub raw_text: Option<String>,
    /// 片段类型。
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<f64>,
    /// 业务 ID，被关联对象的 ID。
    #[serde(rename = "biz_id", skip_serializing_if = "Option::is_none")]
    pub biz_id: Option<f64>,
}

impl GetSocialBilibiliVideoinfo200ResponseDescV2Inner {
    pub fn new() -> GetSocialBilibiliVideoinfo200ResponseDescV2Inner {
        GetSocialBilibiliVideoinfo200ResponseDescV2Inner {
            raw_text: None,
            r#type: None,
            biz_id: None,
        }
    }
}

