/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetNetworkUrlstatus200ResponseOneOf1 : 当目标 URL 不可达或请求失败（如 DNS 失败、超时、连接失败）时，`status` 为 `0`。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNetworkUrlstatus200ResponseOneOf1 {
    /// 目标不可达或请求失败时固定为 0。
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl GetNetworkUrlstatus200ResponseOneOf1 {
    /// 当目标 URL 不可达或请求失败（如 DNS 失败、超时、连接失败）时，`status` 为 `0`。
    pub fn new() -> GetNetworkUrlstatus200ResponseOneOf1 {
        GetNetworkUrlstatus200ResponseOneOf1 {
            status: None,
            url: None,
        }
    }
}

