/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWebparseMetadata200Response {
    #[serde(rename = "page_url", skip_serializing_if = "Option::is_none")]
    pub page_url: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "keywords", skip_serializing_if = "Option::is_none")]
    pub keywords: Option<Vec<String>>,
    #[serde(rename = "favicon_url", skip_serializing_if = "Option::is_none")]
    pub favicon_url: Option<String>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    #[serde(rename = "published_time", skip_serializing_if = "Option::is_none")]
    pub published_time: Option<String>,
    #[serde(rename = "canonical_url", skip_serializing_if = "Option::is_none")]
    pub canonical_url: Option<String>,
    #[serde(rename = "generator", skip_serializing_if = "Option::is_none")]
    pub generator: Option<String>,
    #[serde(rename = "open_graph", skip_serializing_if = "Option::is_none")]
    pub open_graph: Option<serde_json::Value>,
}

impl GetWebparseMetadata200Response {
    pub fn new() -> GetWebparseMetadata200Response {
        GetWebparseMetadata200Response {
            page_url: None,
            title: None,
            description: None,
            keywords: None,
            favicon_url: None,
            language: None,
            author: None,
            published_time: None,
            canonical_url: None,
            generator: None,
            open_graph: None,
        }
    }
}

