/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSocialBilibiliArchives200ResponseVideosInner {
    /// 视频AID
    #[serde(rename = "aid", skip_serializing_if = "Option::is_none")]
    pub aid: Option<i32>,
    /// BV号
    #[serde(rename = "bvid", skip_serializing_if = "Option::is_none")]
    pub bvid: Option<String>,
    /// 标题
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// 封面URL
    #[serde(rename = "cover", skip_serializing_if = "Option::is_none")]
    pub cover: Option<String>,
    /// 时长(秒)
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    /// 播放量
    #[serde(rename = "play_count", skip_serializing_if = "Option::is_none")]
    pub play_count: Option<i32>,
    /// 发布时间戳
    #[serde(rename = "publish_time", skip_serializing_if = "Option::is_none")]
    pub publish_time: Option<i32>,
    /// 创建时间戳
    #[serde(rename = "create_time", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<i32>,
    /// 视频状态
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<i32>,
    /// 是否付费视频。0=免费，1=付费
    #[serde(rename = "is_ugc_pay", skip_serializing_if = "Option::is_none")]
    pub is_ugc_pay: Option<i32>,
    /// 是否为互动视频
    #[serde(rename = "is_interactive", skip_serializing_if = "Option::is_none")]
    pub is_interactive: Option<bool>,
}

impl GetSocialBilibiliArchives200ResponseVideosInner {
    pub fn new() -> GetSocialBilibiliArchives200ResponseVideosInner {
        GetSocialBilibiliArchives200ResponseVideosInner {
            aid: None,
            bvid: None,
            title: None,
            cover: None,
            duration: None,
            play_count: None,
            publish_time: None,
            create_time: None,
            state: None,
            is_ugc_pay: None,
            is_interactive: None,
        }
    }
}

