/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSocialBilibiliVideoinfo200ResponseStaffInner {
    /// 成员 UID。
    #[serde(rename = "mid", skip_serializing_if = "Option::is_none")]
    pub mid: Option<f64>,
    /// 成员角色标题。
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// 成员昵称。
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 成员头像链接。
    #[serde(rename = "face", skip_serializing_if = "Option::is_none")]
    pub face: Option<String>,
    /// 成员粉丝数。
    #[serde(rename = "follower", skip_serializing_if = "Option::is_none")]
    pub follower: Option<f64>,
}

impl GetSocialBilibiliVideoinfo200ResponseStaffInner {
    pub fn new() -> GetSocialBilibiliVideoinfo200ResponseStaffInner {
        GetSocialBilibiliVideoinfo200ResponseStaffInner {
            mid: None,
            title: None,
            name: None,
            face: None,
            follower: None,
        }
    }
}

