/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetNetworkWhois200ResponseOneOf : ### 文本格式响应 当 `format=text` 或未指定时，`whois` 字段包含原始的WHOIS查询文本。这保留了最完整的信息，适合需要自行解析或展示原始数据的场景。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNetworkWhois200ResponseOneOf {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    /// **WHOIS原始文本**  返回未经处理的原始WHOIS查询结果文本。
    #[serde(rename = "whois", skip_serializing_if = "Option::is_none")]
    pub whois: Option<String>,
}

impl GetNetworkWhois200ResponseOneOf {
    /// ### 文本格式响应 当 `format=text` 或未指定时，`whois` 字段包含原始的WHOIS查询文本。这保留了最完整的信息，适合需要自行解析或展示原始数据的场景。
    pub fn new() -> GetNetworkWhois200ResponseOneOf {
        GetNetworkWhois200ResponseOneOf {
            code: None,
            whois: None,
        }
    }
}

