/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStatusUsage200ResponseAnyOfUnaggregated {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "oldest_log", skip_serializing_if = "Option::is_none")]
    pub oldest_log: Option<String>,
}

impl GetStatusUsage200ResponseAnyOfUnaggregated {
    pub fn new() -> GetStatusUsage200ResponseAnyOfUnaggregated {
        GetStatusUsage200ResponseAnyOfUnaggregated {
            count: None,
            oldest_log: None,
        }
    }
}

