/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSocialBilibiliVideoinfo200ResponseUgcSeason : 合集信息。若视频不属于合集则为 null。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSocialBilibiliVideoinfo200ResponseUgcSeason {
    /// 合集 ID。
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<f64>,
    /// 合集标题。
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// 合集封面。
    #[serde(rename = "cover", skip_serializing_if = "Option::is_none")]
    pub cover: Option<String>,
    /// 合集作者 UID。
    #[serde(rename = "mid", skip_serializing_if = "Option::is_none")]
    pub mid: Option<f64>,
    /// 合集简介。
    #[serde(rename = "intro", skip_serializing_if = "Option::is_none")]
    pub intro: Option<String>,
    /// 合集内视频数量。
    #[serde(rename = "ep_count", skip_serializing_if = "Option::is_none")]
    pub ep_count: Option<f64>,
}

impl GetSocialBilibiliVideoinfo200ResponseUgcSeason {
    /// 合集信息。若视频不属于合集则为 null。
    pub fn new() -> GetSocialBilibiliVideoinfo200ResponseUgcSeason {
        GetSocialBilibiliVideoinfo200ResponseUgcSeason {
            id: None,
            title: None,
            cover: None,
            mid: None,
            intro: None,
            ep_count: None,
        }
    }
}

