/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscHotboard200ResponseOneOf {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// 热榜更新时间。时光机无匹配快照时可能为空字符串。
    #[serde(rename = "update_time", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
    /// 时光机模式返回的快照实际时间戳（毫秒）。当前热榜模式下通常不返回。
    #[serde(rename = "snapshot_time", skip_serializing_if = "Option::is_none")]
    pub snapshot_time: Option<i32>,
    /// 热榜条目列表。
    #[serde(rename = "list", skip_serializing_if = "Option::is_none")]
    pub list: Option<Vec<models::GetMiscHotboard200ResponseOneOfListInner>>,
}

impl GetMiscHotboard200ResponseOneOf {
    pub fn new() -> GetMiscHotboard200ResponseOneOf {
        GetMiscHotboard200ResponseOneOf {
            r#type: None,
            update_time: None,
            snapshot_time: None,
            list: None,
        }
    }
}

