/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetHistoryProgrammer200ResponseEventsInner {
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<i32>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "importance", skip_serializing_if = "Option::is_none")]
    pub importance: Option<i32>,
    #[serde(rename = "relevance_score", skip_serializing_if = "Option::is_none")]
    pub relevance_score: Option<f64>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl GetHistoryProgrammer200ResponseEventsInner {
    pub fn new() -> GetHistoryProgrammer200ResponseEventsInner {
        GetHistoryProgrammer200ResponseEventsInner {
            year: None,
            title: None,
            description: None,
            category: None,
            importance: None,
            relevance_score: None,
            url: None,
        }
    }
}

