/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetMiscHolidayCalendar200ResponseQuery : 请求参数回显。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscHolidayCalendar200ResponseQuery {
    /// 日视图查询参数。date 模式下为 YYYY-MM-DD，其余模式下为空字符串。
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// 节日筛选类型。
    #[serde(rename = "holiday_type", skip_serializing_if = "Option::is_none")]
    pub holiday_type: Option<String>,
    /// 是否开启前后最近节日查询。
    #[serde(rename = "include_nearby", skip_serializing_if = "Option::is_none")]
    pub include_nearby: Option<bool>,
    /// 是否过滤今天之前已经过去的节日。
    #[serde(rename = "exclude_past", skip_serializing_if = "Option::is_none")]
    pub exclude_past: Option<bool>,
    /// 月视图查询参数。month 模式下为 YYYY-MM，其余模式下为空字符串。
    #[serde(rename = "month", skip_serializing_if = "Option::is_none")]
    pub month: Option<String>,
    /// 前后最近节日返回数量上限。
    #[serde(rename = "nearby_limit", skip_serializing_if = "Option::is_none")]
    pub nearby_limit: Option<i32>,
    /// 实际生效的时区。
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// 年视图查询参数。year 模式下为 YYYY，其余模式下为空字符串。
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<String>,
}

impl GetMiscHolidayCalendar200ResponseQuery {
    /// 请求参数回显。
    pub fn new() -> GetMiscHolidayCalendar200ResponseQuery {
        GetMiscHolidayCalendar200ResponseQuery {
            date: None,
            holiday_type: None,
            include_nearby: None,
            exclude_past: None,
            month: None,
            nearby_limit: None,
            timezone: None,
            year: None,
        }
    }
}

