/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscHolidayCalendar400Response {
    /// 业务状态码，400 表示请求参数错误。
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    /// 具体错误原因提示。
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl GetMiscHolidayCalendar400Response {
    pub fn new() -> GetMiscHolidayCalendar400Response {
        GetMiscHolidayCalendar400Response {
            code: None,
            message: None,
        }
    }
}

