/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscTrackingQuery200ResponseDataTracksInner {
    /// 物流更新时间
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    /// 物流状态描述
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
}

impl GetMiscTrackingQuery200ResponseDataTracksInner {
    pub fn new() -> GetMiscTrackingQuery200ResponseDataTracksInner {
        GetMiscTrackingQuery200ResponseDataTracksInner {
            time: None,
            context: None,
        }
    }
}

