/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscHotboard200ResponseOneOf1 {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// 搜索关键词。
    #[serde(rename = "keyword", skip_serializing_if = "Option::is_none")]
    pub keyword: Option<String>,
    /// 匹配到的结果数量。
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// 搜索结果数组。
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::GetMiscHotboard200ResponseOneOf1ResultsInner>>,
}

impl GetMiscHotboard200ResponseOneOf1 {
    pub fn new() -> GetMiscHotboard200ResponseOneOf1 {
        GetMiscHotboard200ResponseOneOf1 {
            r#type: None,
            keyword: None,
            count: None,
            results: None,
        }
    }
}

