/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSocialBilibiliVideoinfo200ResponseSubtitle : 字幕信息。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSocialBilibiliVideoinfo200ResponseSubtitle {
    /// 是否允许观众投稿字幕。
    #[serde(rename = "allow_submit", skip_serializing_if = "Option::is_none")]
    pub allow_submit: Option<bool>,
    /// 字幕列表。
    #[serde(rename = "list", skip_serializing_if = "Option::is_none")]
    pub list: Option<Vec<models::GetSocialBilibiliVideoinfo200ResponseSubtitleListInner>>,
}

impl GetSocialBilibiliVideoinfo200ResponseSubtitle {
    /// 字幕信息。
    pub fn new() -> GetSocialBilibiliVideoinfo200ResponseSubtitle {
        GetSocialBilibiliVideoinfo200ResponseSubtitle {
            allow_submit: None,
            list: None,
        }
    }
}

