/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetMiscWeather200ResponseLifeIndicesAirPurifier : 空气净化器指数
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscWeather200ResponseLifeIndicesAirPurifier {
    #[serde(rename = "level", skip_serializing_if = "Option::is_none")]
    pub level: Option<String>,
    #[serde(rename = "brief", skip_serializing_if = "Option::is_none")]
    pub brief: Option<String>,
    #[serde(rename = "advice", skip_serializing_if = "Option::is_none")]
    pub advice: Option<String>,
}

impl GetMiscWeather200ResponseLifeIndicesAirPurifier {
    /// 空气净化器指数
    pub fn new() -> GetMiscWeather200ResponseLifeIndicesAirPurifier {
        GetMiscWeather200ResponseLifeIndicesAirPurifier {
            level: None,
            brief: None,
            advice: None,
        }
    }
}

