/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscHotboard200ResponseOneOf2 {
    /// 支持历史数据的平台列表。
    #[serde(rename = "sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<String>>,
}

impl GetMiscHotboard200ResponseOneOf2 {
    pub fn new() -> GetMiscHotboard200ResponseOneOf2 {
        GetMiscHotboard200ResponseOneOf2 {
            sources: None,
        }
    }
}

