/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscDistrict200Response {
    /// 结果总数。
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// 结果列表。
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::GetMiscDistrict200ResponseResultsInner>>,
}

impl GetMiscDistrict200Response {
    pub fn new() -> GetMiscDistrict200Response {
        GetMiscDistrict200Response {
            total: None,
            results: None,
        }
    }
}

