/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetGithubRepo200ResponseLatestRelease : 仓库最新发布版本信息，如果没有 Release 则为 null。可用于实现应用更新检查功能。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGithubRepo200ResponseLatestRelease {
    /// 版本标签
    #[serde(rename = "tag_name", skip_serializing_if = "Option::is_none")]
    pub tag_name: Option<String>,
    /// 发布名称
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 发布时间
    #[serde(rename = "published_at", skip_serializing_if = "Option::is_none")]
    pub published_at: Option<String>,
    /// Release 页面链接
    #[serde(rename = "html_url", skip_serializing_if = "Option::is_none")]
    pub html_url: Option<String>,
    /// 是否为预发布版本
    #[serde(rename = "prerelease", skip_serializing_if = "Option::is_none")]
    pub prerelease: Option<bool>,
    /// 是否为草稿
    #[serde(rename = "draft", skip_serializing_if = "Option::is_none")]
    pub draft: Option<bool>,
}

impl GetGithubRepo200ResponseLatestRelease {
    /// 仓库最新发布版本信息，如果没有 Release 则为 null。可用于实现应用更新检查功能。
    pub fn new() -> GetGithubRepo200ResponseLatestRelease {
        GetGithubRepo200ResponseLatestRelease {
            tag_name: None,
            name: None,
            published_at: None,
            html_url: None,
            prerelease: None,
            draft: None,
        }
    }
}

