/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNetworkPingmyip200Response {
    /// 平均延迟(ms)
    #[serde(rename = "avg", skip_serializing_if = "Option::is_none")]
    pub avg: Option<f64>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(rename = "ip", skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// 最大延迟(ms)
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<f64>,
    /// 最小延迟(ms)
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
}

impl GetNetworkPingmyip200Response {
    pub fn new() -> GetNetworkPingmyip200Response {
        GetNetworkPingmyip200Response {
            avg: None,
            code: None,
            host: None,
            ip: None,
            location: None,
            max: None,
            min: None,
        }
    }
}

