/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGithubUser200ResponseOrganizationsInner {
    /// 组织登录名。
    #[serde(rename = "login", skip_serializing_if = "Option::is_none")]
    pub login: Option<String>,
    /// 组织简介。
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// 组织主页链接。
    #[serde(rename = "html_url", skip_serializing_if = "Option::is_none")]
    pub html_url: Option<String>,
    /// 组织头像链接。
    #[serde(rename = "avatar_url", skip_serializing_if = "Option::is_none")]
    pub avatar_url: Option<String>,
}

impl GetGithubUser200ResponseOrganizationsInner {
    pub fn new() -> GetGithubUser200ResponseOrganizationsInner {
        GetGithubUser200ResponseOrganizationsInner {
            login: None,
            description: None,
            html_url: None,
            avatar_url: None,
        }
    }
}

