/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSocialBilibiliVideoinfo200ResponseRights : 视频权限开关（0 或 1）。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSocialBilibiliVideoinfo200ResponseRights {
    /// 是否可以承包/付费（老字段）。
    #[serde(rename = "bp", skip_serializing_if = "Option::is_none")]
    pub bp: Option<f64>,
    /// 是否允许付费充电。
    #[serde(rename = "elec", skip_serializing_if = "Option::is_none")]
    pub elec: Option<f64>,
    /// 是否允许缓存/下载。
    #[serde(rename = "download", skip_serializing_if = "Option::is_none")]
    pub download: Option<f64>,
    /// 是否为电影。
    #[serde(rename = "movie", skip_serializing_if = "Option::is_none")]
    pub movie: Option<f64>,
    /// 是否需要付费观看。
    #[serde(rename = "pay", skip_serializing_if = "Option::is_none")]
    pub pay: Option<f64>,
    /// 高码率相关老字段。
    #[serde(rename = "hd5", skip_serializing_if = "Option::is_none")]
    pub hd5: Option<f64>,
    /// 是否禁止转载（1 表示禁止）。
    #[serde(rename = "no_reprint", skip_serializing_if = "Option::is_none")]
    pub no_reprint: Option<f64>,
    /// 是否允许自动播放。
    #[serde(rename = "autoplay", skip_serializing_if = "Option::is_none")]
    pub autoplay: Option<f64>,
    /// 是否为 UGC 付费内容。
    #[serde(rename = "ugc_pay", skip_serializing_if = "Option::is_none")]
    pub ugc_pay: Option<f64>,
    /// 是否为合作视频。
    #[serde(rename = "is_cooperation", skip_serializing_if = "Option::is_none")]
    pub is_cooperation: Option<f64>,
    /// 是否允许付费内容试看。
    #[serde(rename = "ugc_pay_preview", skip_serializing_if = "Option::is_none")]
    pub ugc_pay_preview: Option<f64>,
    /// 背景相关控制字段。
    #[serde(rename = "no_background", skip_serializing_if = "Option::is_none")]
    pub no_background: Option<f64>,
    /// 是否为纯净模式。
    #[serde(rename = "clean_mode", skip_serializing_if = "Option::is_none")]
    pub clean_mode: Option<f64>,
    /// 互动剧情相关字段。
    #[serde(rename = "is_stein_gate", skip_serializing_if = "Option::is_none")]
    pub is_stein_gate: Option<f64>,
    /// 是否为 360° 全景视频。
    #[serde(rename = "is_360", skip_serializing_if = "Option::is_none")]
    pub is_360: Option<f64>,
    /// 是否禁止分享（1 表示禁止）。
    #[serde(rename = "no_share", skip_serializing_if = "Option::is_none")]
    pub no_share: Option<f64>,
    /// 是否为付费视频。
    #[serde(rename = "arc_pay", skip_serializing_if = "Option::is_none")]
    pub arc_pay: Option<f64>,
    /// 付费视频是否允许免费试看。
    #[serde(rename = "free_watch", skip_serializing_if = "Option::is_none")]
    pub free_watch: Option<f64>,
}

impl GetSocialBilibiliVideoinfo200ResponseRights {
    /// 视频权限开关（0 或 1）。
    pub fn new() -> GetSocialBilibiliVideoinfo200ResponseRights {
        GetSocialBilibiliVideoinfo200ResponseRights {
            bp: None,
            elec: None,
            download: None,
            movie: None,
            pay: None,
            hd5: None,
            no_reprint: None,
            autoplay: None,
            ugc_pay: None,
            is_cooperation: None,
            ugc_pay_preview: None,
            no_background: None,
            clean_mode: None,
            is_stein_gate: None,
            is_360: None,
            no_share: None,
            arc_pay: None,
            free_watch: None,
        }
    }
}

