/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscHolidayCalendar200ResponseNearbyPreviousInner {
    /// 聚合日期。
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// 该日期上的节日事件列表。
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<models::GetMiscHolidayCalendar200ResponseNearbyPreviousInnerEventsInner>>,
}

impl GetMiscHolidayCalendar200ResponseNearbyPreviousInner {
    pub fn new() -> GetMiscHolidayCalendar200ResponseNearbyPreviousInner {
        GetMiscHolidayCalendar200ResponseNearbyPreviousInner {
            date: None,
            events: None,
        }
    }
}

