/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner {
    /// 当天日期。
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// 当天的贡献次数。
    #[serde(rename = "contribution_count", skip_serializing_if = "Option::is_none")]
    pub contribution_count: Option<i32>,
    /// 当天贡献等级对应的颜色值。
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    /// 星期索引，0 表示周日，6 表示周六。
    #[serde(rename = "weekday", skip_serializing_if = "Option::is_none")]
    pub weekday: Option<i32>,
}

impl GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner {
    pub fn new() -> GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner {
        GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner {
            date: None,
            contribution_count: None,
            color: None,
            weekday: None,
        }
    }
}

