/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSocialBilibiliReplies200ResponseRepliesInnerContent : 评论内容。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSocialBilibiliReplies200ResponseRepliesInnerContent {
    /// 评论的文本内容。
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl GetSocialBilibiliReplies200ResponseRepliesInnerContent {
    /// 评论内容。
    pub fn new() -> GetSocialBilibiliReplies200ResponseRepliesInnerContent {
        GetSocialBilibiliReplies200ResponseRepliesInnerContent {
            message: None,
        }
    }
}

