/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSearchEngines200Response {
    #[serde(rename = "engine", skip_serializing_if = "Option::is_none")]
    pub engine: Option<Box<models::GetSearchEngines200ResponseEngine>>,
    #[serde(rename = "limits", skip_serializing_if = "Option::is_none")]
    pub limits: Option<Box<models::GetSearchEngines200ResponseLimits>>,
    /// 支持的所有参数说明列表
    #[serde(rename = "supported_parameters", skip_serializing_if = "Option::is_none")]
    pub supported_parameters: Option<Vec<String>>,
}

impl GetSearchEngines200Response {
    pub fn new() -> GetSearchEngines200Response {
        GetSearchEngines200Response {
            engine: None,
            limits: None,
            supported_parameters: None,
        }
    }
}

