/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscWeather200Response {
    #[serde(rename = "adcode", skip_serializing_if = "Option::is_none")]
    pub adcode: Option<String>,
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(rename = "humidity", skip_serializing_if = "Option::is_none")]
    pub humidity: Option<i32>,
    #[serde(rename = "province", skip_serializing_if = "Option::is_none")]
    pub province: Option<String>,
    #[serde(rename = "report_time", skip_serializing_if = "Option::is_none")]
    pub report_time: Option<String>,
    #[serde(rename = "temperature", skip_serializing_if = "Option::is_none")]
    pub temperature: Option<i32>,
    #[serde(rename = "weather", skip_serializing_if = "Option::is_none")]
    pub weather: Option<String>,
    #[serde(rename = "wind_direction", skip_serializing_if = "Option::is_none")]
    pub wind_direction: Option<String>,
    #[serde(rename = "wind_power", skip_serializing_if = "Option::is_none")]
    pub wind_power: Option<String>,
}

impl GetMiscWeather200Response {
    pub fn new() -> GetMiscWeather200Response {
        GetMiscWeather200Response {
            adcode: None,
            city: None,
            humidity: None,
            province: None,
            report_time: None,
            temperature: None,
            weather: None,
            wind_direction: None,
            wind_power: None,
        }
    }
}

