/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGameMinecraftUserinfo200Response {
    /// 状态码，200代表成功。
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    /// 玩家当前使用的皮肤图片URL。
    #[serde(rename = "skin_url", skip_serializing_if = "Option::is_none")]
    pub skin_url: Option<String>,
    /// 玩家当前的准确用户名（注意大小写可能与输入不同）。
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// 玩家的32位无破折号UUID。
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

impl GetGameMinecraftUserinfo200Response {
    pub fn new() -> GetGameMinecraftUserinfo200Response {
        GetGameMinecraftUserinfo200Response {
            code: None,
            skin_url: None,
            username: None,
            uuid: None,
        }
    }
}

