/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGameMinecraftServerstatus200ResponseOnlinePlayersInner {
    /// 玩家名称。
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 玩家的 UUID。部分服务器可能不返回这个字段。
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

impl GetGameMinecraftServerstatus200ResponseOnlinePlayersInner {
    pub fn new() -> GetGameMinecraftServerstatus200ResponseOnlinePlayersInner {
        GetGameMinecraftServerstatus200ResponseOnlinePlayersInner {
            name: None,
            uuid: None,
        }
    }
}

