/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetMiscHolidayCalendar200ResponseNearby : 前后最近节日，仅 include_nearby=true 且 date 模式返回。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscHolidayCalendar200ResponseNearby {
    /// 当前查询日期之前最近的节日列表（按时间倒序）。
    #[serde(rename = "previous", skip_serializing_if = "Option::is_none")]
    pub previous: Option<Vec<models::GetMiscHolidayCalendar200ResponseNearbyPreviousInner>>,
    /// 当前查询日期之后最近的节日列表（按时间正序）。
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<Vec<models::GetMiscHolidayCalendar200ResponseNearbyNextInner>>,
}

impl GetMiscHolidayCalendar200ResponseNearby {
    /// 前后最近节日，仅 include_nearby=true 且 date 模式返回。
    pub fn new() -> GetMiscHolidayCalendar200ResponseNearby {
        GetMiscHolidayCalendar200ResponseNearby {
            previous: None,
            next: None,
        }
    }
}

