/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSearchEngines200ResponseLimits : 搜索结果数量限制
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSearchEngines200ResponseLimits {
    /// 默认返回结果数
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<i32>,
    /// 最大返回结果数
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<i32>,
}

impl GetSearchEngines200ResponseLimits {
    /// 搜索结果数量限制
    pub fn new() -> GetSearchEngines200ResponseLimits {
        GetSearchEngines200ResponseLimits {
            default: None,
            max: None,
        }
    }
}

