/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscTrackingQuery200ResponseData {
    /// 快递单号
    #[serde(rename = "tracking_number", skip_serializing_if = "Option::is_none")]
    pub tracking_number: Option<String>,
    /// 快递公司编码
    #[serde(rename = "carrier_code", skip_serializing_if = "Option::is_none")]
    pub carrier_code: Option<String>,
    /// 快递公司名称
    #[serde(rename = "carrier_name", skip_serializing_if = "Option::is_none")]
    pub carrier_name: Option<String>,
    /// 物流轨迹数量
    #[serde(rename = "track_count", skip_serializing_if = "Option::is_none")]
    pub track_count: Option<i32>,
    /// 物流轨迹列表，按时间倒序排列
    #[serde(rename = "tracks", skip_serializing_if = "Option::is_none")]
    pub tracks: Option<Vec<models::GetMiscTrackingQuery200ResponseDataTracksInner>>,
}

impl GetMiscTrackingQuery200ResponseData {
    pub fn new() -> GetMiscTrackingQuery200ResponseData {
        GetMiscTrackingQuery200ResponseData {
            tracking_number: None,
            carrier_code: None,
            carrier_name: None,
            track_count: None,
            tracks: None,
        }
    }
}

