/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSearchEngines200ResponseEngine : 搜索引擎的基本信息
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSearchEngines200ResponseEngine {
    /// 引擎标识名称
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 引擎显示名称
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// 引擎描述
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// 引擎是否可用
    #[serde(rename = "available", skip_serializing_if = "Option::is_none")]
    pub available: Option<bool>,
    /// 引擎版本号
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// 支持的特性列表
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<String>>,
}

impl GetSearchEngines200ResponseEngine {
    /// 搜索引擎的基本信息
    pub fn new() -> GetSearchEngines200ResponseEngine {
        GetSearchEngines200ResponseEngine {
            name: None,
            display_name: None,
            description: None,
            available: None,
            version: None,
            features: None,
        }
    }
}

