/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSocialBilibiliReplies200ResponsePage : 分页信息概览。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSocialBilibiliReplies200ResponsePage {
    /// 当前所在的页码。
    #[serde(rename = "num", skip_serializing_if = "Option::is_none")]
    pub num: Option<f64>,
    /// 每页的项数。
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<f64>,
    /// 根评论（即直接评论视频的评论）的总数。
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<f64>,
    /// 评论区总评论数，包含了所有的楼中楼回复。
    #[serde(rename = "acount", skip_serializing_if = "Option::is_none")]
    pub acount: Option<f64>,
}

impl GetSocialBilibiliReplies200ResponsePage {
    /// 分页信息概览。
    pub fn new() -> GetSocialBilibiliReplies200ResponsePage {
        GetSocialBilibiliReplies200ResponsePage {
            num: None,
            size: None,
            count: None,
            acount: None,
        }
    }
}

