/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNetworkDns200ResponseRecordsInner {
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "flag", skip_serializing_if = "Option::is_none")]
    pub flag: Option<i32>,
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    #[serde(rename = "pri", skip_serializing_if = "Option::is_none")]
    pub pri: Option<i32>,
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
}

impl GetNetworkDns200ResponseRecordsInner {
    pub fn new() -> GetNetworkDns200ResponseRecordsInner {
        GetNetworkDns200ResponseRecordsInner {
            content: None,
            flag: None,
            port: None,
            pri: None,
            tag: None,
            target: None,
            weight: None,
        }
    }
}

