/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscHolidayCalendar200ResponseDataNearbyNextInner {
    /// 事件日期。
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// 事件名称。
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 事件类型。
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl GetMiscHolidayCalendar200ResponseDataNearbyNextInner {
    pub fn new() -> GetMiscHolidayCalendar200ResponseDataNearbyNextInner {
        GetMiscHolidayCalendar200ResponseDataNearbyNextInner {
            date: None,
            name: None,
            r#type: None,
        }
    }
}

