/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGameSteamSummary200Response {
    /// 32x32 像素的小尺寸头像URL。
    #[serde(rename = "avatar", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
    /// 184x184 像素的大尺寸头像URL。
    #[serde(rename = "avatarfull", skip_serializing_if = "Option::is_none")]
    pub avatarfull: Option<String>,
    /// 64x64 像素的中等尺寸头像URL。
    #[serde(rename = "avatarmedium", skip_serializing_if = "Option::is_none")]
    pub avatarmedium: Option<String>,
    /// 状态码，200代表成功。
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    /// 社区资料的可见性状态: 1=私密, 3=公开。
    #[serde(rename = "communityvisibilitystate", skip_serializing_if = "Option::is_none")]
    pub communityvisibilitystate: Option<i32>,
    /// 用户个人资料中设置的国家代码 (ISO 3166-1)，前提是用户已设置并公开。
    #[serde(rename = "loccountrycode", skip_serializing_if = "Option::is_none")]
    pub loccountrycode: Option<String>,
    /// 玩家的当前昵称。
    #[serde(rename = "personaname", skip_serializing_if = "Option::is_none")]
    pub personaname: Option<String>,
    /// 用户当前的在线状态: 0-离线, 1-在线, 2-忙碌, 3-离开, 4-打盹, 5-想交易, 6-想玩。
    #[serde(rename = "personastate", skip_serializing_if = "Option::is_none")]
    pub personastate: Option<i32>,
    /// 玩家设置的主要部落的64位ID。
    #[serde(rename = "primaryclanid", skip_serializing_if = "Option::is_none")]
    pub primaryclanid: Option<String>,
    /// 如果用户设置了个人资料，则为1。
    #[serde(rename = "profilestate", skip_serializing_if = "Option::is_none")]
    pub profilestate: Option<i32>,
    /// 用户的Steam社区个人资料页完整URL。
    #[serde(rename = "profileurl", skip_serializing_if = "Option::is_none")]
    pub profileurl: Option<String>,
    /// 用户的真实姓名，前提是用户已设置并公开。
    #[serde(rename = "realname", skip_serializing_if = "Option::is_none")]
    pub realname: Option<String>,
    /// 被查询用户的64位SteamID。
    #[serde(rename = "steamid", skip_serializing_if = "Option::is_none")]
    pub steamid: Option<String>,
    /// 账户创建时的Unix时间戳（秒）。
    #[serde(rename = "timecreated", skip_serializing_if = "Option::is_none")]
    pub timecreated: Option<i32>,
    /// 我们为你格式化好的账户创建时间，更直观。
    #[serde(rename = "timecreated_str", skip_serializing_if = "Option::is_none")]
    pub timecreated_str: Option<String>,
}

impl GetGameSteamSummary200Response {
    pub fn new() -> GetGameSteamSummary200Response {
        GetGameSteamSummary200Response {
            avatar: None,
            avatarfull: None,
            avatarmedium: None,
            code: None,
            communityvisibilitystate: None,
            loccountrycode: None,
            personaname: None,
            personastate: None,
            primaryclanid: None,
            profilestate: None,
            profileurl: None,
            realname: None,
            steamid: None,
            timecreated: None,
            timecreated_str: None,
        }
    }
}

