/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetMiscHotboard200Response {
    GetMiscHotboard200ResponseOneOf(Box<models::GetMiscHotboard200ResponseOneOf>),
    GetMiscHotboard200ResponseOneOf1(Box<models::GetMiscHotboard200ResponseOneOf1>),
    GetMiscHotboard200ResponseOneOf2(Box<models::GetMiscHotboard200ResponseOneOf2>),
}

impl Default for GetMiscHotboard200Response {
    fn default() -> Self {
        Self::GetMiscHotboard200ResponseOneOf(Default::default())
    }
}

