/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGameMinecraftServerstatus200Response {
    /// 状态码，200代表成功。
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    /// 服务器图标的 Base64 Data URI。你可以直接在 `<img>` 标签的 `src` 属性中使用它。
    #[serde(rename = "favicon_url", skip_serializing_if = "Option::is_none")]
    pub favicon_url: Option<String>,
    /// 服务器解析后的IP地址。
    #[serde(rename = "ip", skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    /// 服务器配置的最大玩家容量。
    #[serde(rename = "max_players", skip_serializing_if = "Option::is_none")]
    pub max_players: Option<i32>,
    /// 纯文本格式的服务器MOTD（每日消息），去除了所有颜色和格式代码。
    #[serde(rename = "motd_clean", skip_serializing_if = "Option::is_none")]
    pub motd_clean: Option<String>,
    /// HTML格式的服务器MOTD，保留了颜色和样式，方便你在网页上直接渲染。
    #[serde(rename = "motd_html", skip_serializing_if = "Option::is_none")]
    pub motd_html: Option<String>,
    /// 服务器当前是否在线。
    #[serde(rename = "online", skip_serializing_if = "Option::is_none")]
    pub online: Option<bool>,
    /// 当前在线的玩家数量。
    #[serde(rename = "players", skip_serializing_if = "Option::is_none")]
    pub players: Option<i32>,
    /// 服务器使用的端口。
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    /// 服务器报告的版本信息。
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl GetGameMinecraftServerstatus200Response {
    pub fn new() -> GetGameMinecraftServerstatus200Response {
        GetGameMinecraftServerstatus200Response {
            code: None,
            favicon_url: None,
            ip: None,
            max_players: None,
            motd_clean: None,
            motd_html: None,
            online: None,
            players: None,
            port: None,
            version: None,
        }
    }
}

