/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscWeather200ResponseHourlyForecastInner {
    /// 预报时间（ISO8601 或 YYYY-MM-DD HH:MM）
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    /// 温度 °C
    #[serde(rename = "temperature", skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    /// 天气状况
    #[serde(rename = "weather", skip_serializing_if = "Option::is_none")]
    pub weather: Option<String>,
    /// 风向（可选）
    #[serde(rename = "wind_direction", skip_serializing_if = "Option::is_none")]
    pub wind_direction: Option<String>,
    /// 风速 km/h（可选）
    #[serde(rename = "wind_speed", skip_serializing_if = "Option::is_none")]
    pub wind_speed: Option<f64>,
    /// 风力等级（可选）
    #[serde(rename = "wind_scale", skip_serializing_if = "Option::is_none")]
    pub wind_scale: Option<String>,
    /// 湿度 %（可选）
    #[serde(rename = "humidity", skip_serializing_if = "Option::is_none")]
    pub humidity: Option<f64>,
    /// 降水量 mm（可选）
    #[serde(rename = "precip", skip_serializing_if = "Option::is_none")]
    pub precip: Option<f64>,
    /// 体感温度 °C（可选）
    #[serde(rename = "feels_like", skip_serializing_if = "Option::is_none")]
    pub feels_like: Option<f64>,
    /// 能见度 km（可选）
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<f64>,
    /// 降水概率 %（可选）
    #[serde(rename = "pop", skip_serializing_if = "Option::is_none")]
    pub pop: Option<f64>,
    /// 紫外线指数（可选，国内城市通常不返回）
    #[serde(rename = "uv_index", skip_serializing_if = "Option::is_none")]
    pub uv_index: Option<f64>,
}

impl GetMiscWeather200ResponseHourlyForecastInner {
    pub fn new() -> GetMiscWeather200ResponseHourlyForecastInner {
        GetMiscWeather200ResponseHourlyForecastInner {
            time: None,
            temperature: None,
            weather: None,
            wind_direction: None,
            wind_speed: None,
            wind_scale: None,
            humidity: None,
            precip: None,
            feels_like: None,
            visibility: None,
            pop: None,
            uv_index: None,
        }
    }
}

