/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSocialBilibiliUserinfo200ResponseData {
    #[serde(rename = "face", skip_serializing_if = "Option::is_none")]
    pub face: Option<String>,
    #[serde(rename = "level", skip_serializing_if = "Option::is_none")]
    pub level: Option<i32>,
    #[serde(rename = "mid", skip_serializing_if = "Option::is_none")]
    pub mid: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "sex", skip_serializing_if = "Option::is_none")]
    pub sex: Option<String>,
    #[serde(rename = "sign", skip_serializing_if = "Option::is_none")]
    pub sign: Option<String>,
}

impl GetSocialBilibiliUserinfo200ResponseData {
    pub fn new() -> GetSocialBilibiliUserinfo200ResponseData {
        GetSocialBilibiliUserinfo200ResponseData {
            face: None,
            level: None,
            mid: None,
            name: None,
            sex: None,
            sign: None,
        }
    }
}

