/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiscHolidayCalendar200ResponseNearbyNextInner {
    /// 聚合日期。
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// 该日期上的节日事件列表。
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<models::GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInner>>,
}

impl GetMiscHolidayCalendar200ResponseNearbyNextInner {
    pub fn new() -> GetMiscHolidayCalendar200ResponseNearbyNextInner {
        GetMiscHolidayCalendar200ResponseNearbyNextInner {
            date: None,
            events: None,
        }
    }
}

