/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAiTranslateLanguages200ResponsePerformance {
    #[serde(rename = "batch_translation_available", skip_serializing_if = "Option::is_none")]
    pub batch_translation_available: Option<bool>,
    #[serde(rename = "max_batch_size", skip_serializing_if = "Option::is_none")]
    pub max_batch_size: Option<i32>,
    #[serde(rename = "max_text_length", skip_serializing_if = "Option::is_none")]
    pub max_text_length: Option<i32>,
}

impl GetAiTranslateLanguages200ResponsePerformance {
    pub fn new() -> GetAiTranslateLanguages200ResponsePerformance {
        GetAiTranslateLanguages200ResponsePerformance {
            batch_translation_available: None,
            max_batch_size: None,
            max_text_length: None,
        }
    }
}

