/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostSensitiveWordAnalyzeRequest {
    /// 要分析的关键词列表，单次最多100个，每个关键词最长50字符。
    #[serde(rename = "keywords")]
    pub keywords: Vec<String>,
}

impl PostSensitiveWordAnalyzeRequest {
    pub fn new(keywords: Vec<String>) -> PostSensitiveWordAnalyzeRequest {
        PostSensitiveWordAnalyzeRequest {
            keywords,
        }
    }
}

