/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostAnswerbookAskRequest {
    /// 你想要提问的问题
    #[serde(rename = "question")]
    pub question: String,
}

impl PostAnswerbookAskRequest {
    pub fn new(question: String) -> PostAnswerbookAskRequest {
        PostAnswerbookAskRequest {
            question,
        }
    }
}

