/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostAiTranslate200ResponseQualityMetrics : 翻译质量指标，仅在单个翻译时返回。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostAiTranslate200ResponseQualityMetrics {
    #[serde(rename = "fluency_score", skip_serializing_if = "Option::is_none")]
    pub fluency_score: Option<f64>,
    #[serde(rename = "accuracy_score", skip_serializing_if = "Option::is_none")]
    pub accuracy_score: Option<f64>,
    #[serde(rename = "completeness_score", skip_serializing_if = "Option::is_none")]
    pub completeness_score: Option<f64>,
    #[serde(rename = "total_score", skip_serializing_if = "Option::is_none")]
    pub total_score: Option<f64>,
}

impl PostAiTranslate200ResponseQualityMetrics {
    /// 翻译质量指标，仅在单个翻译时返回。
    pub fn new() -> PostAiTranslate200ResponseQualityMetrics {
        PostAiTranslate200ResponseQualityMetrics {
            fluency_score: None,
            accuracy_score: None,
            completeness_score: None,
            total_score: None,
        }
    }
}

