/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostTextMarkdownToHtml400Response {
    PostTextMarkdownToHtml400ResponseOneOf(Box<models::PostTextMarkdownToHtml400ResponseOneOf>),
    Markdown(Box<models::Markdown>),
    PostTextMarkdownToHtml400ResponseOneOf1(Box<models::PostTextMarkdownToHtml400ResponseOneOf1>),
}

impl Default for PostTextMarkdownToHtml400Response {
    fn default() -> Self {
        Self::PostTextMarkdownToHtml400ResponseOneOf(Default::default())
    }
}

