/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostTextBase64DecodeRequest {
    #[serde(rename = "text")]
    pub text: String,
}

impl PostTextBase64DecodeRequest {
    pub fn new(text: String) -> PostTextBase64DecodeRequest {
        PostTextBase64DecodeRequest {
            text,
        }
    }
}

