/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostTextConvert200Response {
    /// 转换结果
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    /// 源格式
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    /// 目标格式
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
    /// 结果长度
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<i32>,
    /// 额外信息（如哈希不可逆提示）
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<String>,
}

impl PostTextConvert200Response {
    pub fn new() -> PostTextConvert200Response {
        PostTextConvert200Response {
            result: None,
            from: None,
            to: None,
            length: None,
            info: None,
        }
    }
}

