/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostTextAesDecryptRequest {
    /// 密钥，长度必须为16、24或32字节，对应AES-128/192/256。
    #[serde(rename = "key")]
    pub key: String,
    /// Base64编码的密文。
    #[serde(rename = "text")]
    pub text: String,
    /// 16字节的IV/Nonce，必须为16个字符
    #[serde(rename = "nonce", skip_serializing_if = "Option::is_none")]
    pub nonce: Option<String>,
}

impl PostTextAesDecryptRequest {
    pub fn new(key: String, text: String) -> PostTextAesDecryptRequest {
        PostTextAesDecryptRequest {
            key,
            text,
            nonce: None,
        }
    }
}

