/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostAiTranslate200ResponsePerformance {
    #[serde(rename = "processing_time_ms", skip_serializing_if = "Option::is_none")]
    pub processing_time_ms: Option<i32>,
    #[serde(rename = "cache_hit", skip_serializing_if = "Option::is_none")]
    pub cache_hit: Option<bool>,
}

impl PostAiTranslate200ResponsePerformance {
    pub fn new() -> PostAiTranslate200ResponsePerformance {
        PostAiTranslate200ResponsePerformance {
            processing_time_ms: None,
            cache_hit: None,
        }
    }
}

