/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostTextMarkdownToPdf413Response {
    Markdown(Box<models::Markdown>),
    PostTextMarkdownToPdf413ResponseOneOf(Box<models::PostTextMarkdownToPdf413ResponseOneOf>),
}

impl Default for PostTextMarkdownToPdf413Response {
    fn default() -> Self {
        Self::Markdown(Default::default())
    }
}

