/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostSearchAggregate200ResponseSourcesInner {
    /// 搜索引擎版本
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 本次搜索引擎调用状态
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// 该搜索引擎返回的结果数
    #[serde(rename = "result_count", skip_serializing_if = "Option::is_none")]
    pub result_count: Option<i32>,
    /// 该搜索引擎的耗时（毫秒）
    #[serde(rename = "elapsed_ms", skip_serializing_if = "Option::is_none")]
    pub elapsed_ms: Option<i32>,
    /// 该搜索源首条结果的域名
    #[serde(rename = "first_result_host", skip_serializing_if = "Option::is_none")]
    pub first_result_host: Option<String>,
}

impl PostSearchAggregate200ResponseSourcesInner {
    pub fn new() -> PostSearchAggregate200ResponseSourcesInner {
        PostSearchAggregate200ResponseSourcesInner {
            name: None,
            status: None,
            result_count: None,
            elapsed_ms: None,
            first_result_host: None,
        }
    }
}

