/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostTranslateStream400Response {
    /// 错误描述
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// 错误码
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<Code>,
}

impl PostTranslateStream400Response {
    pub fn new() -> PostTranslateStream400Response {
        PostTranslateStream400Response {
            error: None,
            code: None,
        }
    }
}
/// 错误码
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest,
    #[serde(rename = "MISSING_QUERY")]
    MissingQuery,
    #[serde(rename = "MISSING_TARGET_LANG")]
    MissingTargetLang,
}

impl Default for Code {
    fn default() -> Code {
        Self::InvalidRequest
    }
}

