/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostImageNsfw200Response {
    /// NSFW 内容的置信度分数，范围 0-1，越高表示越可能是敏感内容。
    #[serde(rename = "nsfw_score", skip_serializing_if = "Option::is_none")]
    pub nsfw_score: Option<f64>,
    /// 正常内容的置信度分数，范围 0-1。
    #[serde(rename = "normal_score", skip_serializing_if = "Option::is_none")]
    pub normal_score: Option<f64>,
    /// 是否判定为 NSFW 内容。
    #[serde(rename = "is_nsfw", skip_serializing_if = "Option::is_none")]
    pub is_nsfw: Option<bool>,
    /// 内容标签，'nsfw' 或 'normal'。
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// 处理建议：'pass'（通过）、'review'（人工复核）、'block'（拦截）。
    #[serde(rename = "suggestion", skip_serializing_if = "Option::is_none")]
    pub suggestion: Option<String>,
    /// 风险等级：'low'、'medium'、'high'。
    #[serde(rename = "risk_level", skip_serializing_if = "Option::is_none")]
    pub risk_level: Option<String>,
    /// 模型对当前判断的置信度。
    #[serde(rename = "confidence", skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    /// 模型推理耗时，单位毫秒。
    #[serde(rename = "inference_time_ms", skip_serializing_if = "Option::is_none")]
    pub inference_time_ms: Option<f64>,
}

impl PostImageNsfw200Response {
    pub fn new() -> PostImageNsfw200Response {
        PostImageNsfw200Response {
            nsfw_score: None,
            normal_score: None,
            is_nsfw: None,
            label: None,
            suggestion: None,
            risk_level: None,
            confidence: None,
            inference_time_ms: None,
        }
    }
}

