/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostTextMarkdownToPdf400Response {
    PostTextMarkdownToHtml400ResponseOneOf(Box<models::PostTextMarkdownToHtml400ResponseOneOf>),
    Markdown(Box<models::Markdown>),
    PostTextMarkdownToPdf400ResponseOneOf(Box<models::PostTextMarkdownToPdf400ResponseOneOf>),
    PostTextMarkdownToPdf400ResponseOneOf1(Box<models::PostTextMarkdownToPdf400ResponseOneOf1>),
    Html(Box<models::Html>),
    PostTextMarkdownToPdf400ResponseOneOf2(Box<models::PostTextMarkdownToPdf400ResponseOneOf2>),
    PostTextMarkdownToPdf400ResponseOneOf3(Box<models::PostTextMarkdownToPdf400ResponseOneOf3>),
}

impl Default for PostTextMarkdownToPdf400Response {
    fn default() -> Self {
        Self::PostTextMarkdownToHtml400ResponseOneOf(Default::default())
    }
}

