/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostSensitiveWordQuickCheckRequest {
    /// 需要检测的文本内容。支持简体和繁体中文。
    #[serde(rename = "text")]
    pub text: String,
}

impl PostSensitiveWordQuickCheckRequest {
    pub fn new(text: String) -> PostSensitiveWordQuickCheckRequest {
        PostSensitiveWordQuickCheckRequest {
            text,
        }
    }
}

