/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostTextMarkdownToHtml200ResponseData {
    /// 转换后的 HTML 字符串，内容是带样式的 HTML 片段。
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
}

impl PostTextMarkdownToHtml200ResponseData {
    pub fn new() -> PostTextMarkdownToHtml200ResponseData {
        PostTextMarkdownToHtml200ResponseData {
            html: None,
        }
    }
}

