/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostTextAesDecryptAdvancedRequest {
    /// 待解密的密文（Base64编码）。此值来自加密接口返回的ciphertext字段
    #[serde(rename = "text")]
    pub text: String,
    /// 解密密钥（必须与加密时相同）
    #[serde(rename = "key")]
    pub key: String,
    /// 加密模式（必须与加密时相同）：GCM/CBC/ECB/CTR/OFB/CFB
    #[serde(rename = "mode")]
    pub mode: Mode,
    /// 填充方式（可选，必须与加密时相同）：PKCS7/ZERO/NONE。GCM模式默认为NONE
    #[serde(rename = "padding", skip_serializing_if = "Option::is_none")]
    pub padding: Option<Padding>,
    /// 初始化向量（非GCM模式必须提供，Base64编码）。此值来自加密接口返回的iv字段
    #[serde(rename = "iv", skip_serializing_if = "Option::is_none")]
    pub iv: Option<String>,
}

impl PostTextAesDecryptAdvancedRequest {
    pub fn new(text: String, key: String, mode: Mode) -> PostTextAesDecryptAdvancedRequest {
        PostTextAesDecryptAdvancedRequest {
            text,
            key,
            mode,
            padding: None,
            iv: None,
        }
    }
}
/// 加密模式（必须与加密时相同）：GCM/CBC/ECB/CTR/OFB/CFB
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "GCM")]
    Gcm,
    #[serde(rename = "CBC")]
    Cbc,
    #[serde(rename = "ECB")]
    Ecb,
    #[serde(rename = "CTR")]
    Ctr,
    #[serde(rename = "OFB")]
    Ofb,
    #[serde(rename = "CFB")]
    Cfb,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Gcm
    }
}
/// 填充方式（可选，必须与加密时相同）：PKCS7/ZERO/NONE。GCM模式默认为NONE
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Padding {
    #[serde(rename = "PKCS7")]
    Pkcs7,
    #[serde(rename = "ZERO")]
    Zero,
    #[serde(rename = "NONE")]
    None,
}

impl Default for Padding {
    fn default() -> Padding {
        Self::Pkcs7
    }
}

