/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostMiscDateDiff200Response {
    /// 总天数
    #[serde(rename = "days", skip_serializing_if = "Option::is_none")]
    pub days: Option<i32>,
    /// 总小时数
    #[serde(rename = "hours", skip_serializing_if = "Option::is_none")]
    pub hours: Option<i32>,
    /// 总分钟数
    #[serde(rename = "minutes", skip_serializing_if = "Option::is_none")]
    pub minutes: Option<i32>,
    /// 总秒数
    #[serde(rename = "seconds", skip_serializing_if = "Option::is_none")]
    pub seconds: Option<i32>,
    /// 总周数
    #[serde(rename = "weeks", skip_serializing_if = "Option::is_none")]
    pub weeks: Option<i32>,
    /// 人性化显示格式
    #[serde(rename = "human_readable", skip_serializing_if = "Option::is_none")]
    pub human_readable: Option<String>,
}

impl PostMiscDateDiff200Response {
    pub fn new() -> PostMiscDateDiff200Response {
        PostMiscDateDiff200Response {
            days: None,
            hours: None,
            minutes: None,
            seconds: None,
            weeks: None,
            human_readable: None,
        }
    }
}

