/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostTextAnalyze200Response {
    #[serde(rename = "characters", skip_serializing_if = "Option::is_none")]
    pub characters: Option<i32>,
    #[serde(rename = "lines", skip_serializing_if = "Option::is_none")]
    pub lines: Option<i32>,
    #[serde(rename = "paragraphs", skip_serializing_if = "Option::is_none")]
    pub paragraphs: Option<i32>,
    #[serde(rename = "sentences", skip_serializing_if = "Option::is_none")]
    pub sentences: Option<i32>,
    #[serde(rename = "words", skip_serializing_if = "Option::is_none")]
    pub words: Option<i32>,
}

impl PostTextAnalyze200Response {
    pub fn new() -> PostTextAnalyze200Response {
        PostTextAnalyze200Response {
            characters: None,
            lines: None,
            paragraphs: None,
            sentences: None,
            words: None,
        }
    }
}

