/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostSearchAggregate200Response {
    /// 实际执行的搜索查询
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// 搜索结果总数
    #[serde(rename = "total_results", skip_serializing_if = "Option::is_none")]
    pub total_results: Option<i32>,
    /// 搜索结果列表
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::PostSearchAggregate200ResponseResultsInner>>,
    /// 各搜索引擎的结果数量统计
    #[serde(rename = "sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<models::PostSearchAggregate200ResponseSourcesInner>>,
    /// 处理耗时（毫秒）
    #[serde(rename = "process_time_ms", skip_serializing_if = "Option::is_none")]
    pub process_time_ms: Option<i32>,
    /// 结果是否来自缓存
    #[serde(rename = "cached", skip_serializing_if = "Option::is_none")]
    pub cached: Option<bool>,
}

impl PostSearchAggregate200Response {
    pub fn new() -> PostSearchAggregate200Response {
        PostSearchAggregate200Response {
            query: None,
            total_results: None,
            results: None,
            sources: None,
            process_time_ms: None,
            cached: None,
        }
    }
}

