/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostTextAesEncryptAdvanced200Response {
    /// 加密后的密文（Base64编码）
    #[serde(rename = "ciphertext", skip_serializing_if = "Option::is_none")]
    pub ciphertext: Option<String>,
    /// 使用的加密模式
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    /// 使用的填充方式
    #[serde(rename = "padding", skip_serializing_if = "Option::is_none")]
    pub padding: Option<String>,
    /// 使用的IV（Base64编码）。GCM模式不返回此字段
    #[serde(rename = "iv", skip_serializing_if = "Option::is_none")]
    pub iv: Option<String>,
}

impl PostTextAesEncryptAdvanced200Response {
    pub fn new() -> PostTextAesEncryptAdvanced200Response {
        PostTextAesEncryptAdvanced200Response {
            ciphertext: None,
            mode: None,
            padding: None,
            iv: None,
        }
    }
}

