/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_search_engines`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSearchEnginesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_sensitive_word_analyze_query`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSensitiveWordAnalyzeQueryError {
    Status400(models::GetSensitiveWordAnalyzeQuery400Response),
    Status401(models::PostSensitiveWordAnalyze401Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_search_aggregate`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostSearchAggregateError {
    Status400(models::PostSearchAggregate400Response),
    Status401(models::PostSearchAggregate401Response),
    Status429(models::PostSearchAggregate429Response),
    Status500(models::PostSearchAggregate500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_sensitive_word_analyze`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostSensitiveWordAnalyzeError {
    Status400(models::PostSensitiveWordAnalyze400Response),
    Status401(models::PostSensitiveWordAnalyze401Response),
    Status429(models::PostSensitiveWordAnalyze429Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_sensitive_word_quick_check`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostSensitiveWordQuickCheckError {
    Status400(models::PostTextAnalyze400Response),
    UnknownValue(serde_json::Value),
}


/// 获取搜索功能的详细信息，包括支持的能力、参数限制和使用说明。  ## 功能概述  此接口返回搜索功能的完整配置信息，你可以用它来： - 了解当前可用的搜索能力（如站内搜索、文件类型过滤等） - 获取参数的默认值和限制范围 - 查看当前配置版本和可用状态  适合在应用初始化时调用，或用于动态配置搜索界面。       
pub async fn get_search_engines(configuration: &configuration::Configuration, ) -> Result<models::GetSearchEngines200Response, Error<GetSearchEnginesError>> {

    let uri_str = format!("{}/search/engines", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetSearchEngines200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetSearchEngines200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSearchEnginesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 通过URL查询参数分析单个关键词，便于GET请求调用。
pub async fn get_sensitive_word_analyze_query(configuration: &configuration::Configuration, keyword: &str) -> Result<models::PostSensitiveWordAnalyze200Response, Error<GetSensitiveWordAnalyzeQueryError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_keyword = keyword;

    let uri_str = format!("{}/sensitive-word/analyze-query", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("keyword", &p_query_keyword.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostSensitiveWordAnalyze200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostSensitiveWordAnalyze200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSensitiveWordAnalyzeQueryError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 想在你的应用中集成搜索功能？这个接口可以帮你轻松实现实时网页搜索。  ## 功能概述  UAPI Pro Search 可以根据查询内容返回更相关的搜索结果。你可以用它搜索任何关键词，也可以限定在特定网站或特定文件类型中搜索。  - **实时网页搜索**: 毫秒级响应，快速返回搜索结果 - **智能排序**: 根据查询内容返回更相关的结果 - **时间排序**: 支持按发布时间排序，获取最新内容 - **时间范围过滤**: 支持按天/周/月/年过滤结果 - **站内搜索**: 支持 `site:` 操作符，在指定网站内搜索 - **文件类型过滤**: 支持 `filetype:` 操作符，快速找到 PDF、Word 等特定格式文件       
pub async fn post_search_aggregate(configuration: &configuration::Configuration, post_search_aggregate_request: models::PostSearchAggregateRequest) -> Result<models::PostSearchAggregate200Response, Error<PostSearchAggregateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_post_search_aggregate_request = post_search_aggregate_request;

    let uri_str = format!("{}/search/aggregate", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_post_search_aggregate_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostSearchAggregate200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostSearchAggregate200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostSearchAggregateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 分析单个或多个关键词的敏感程度，返回标准化风险标签与置信度结果。  ## 功能概述  - **风险分析**: 结合文本内容给出语义层面的风险判断。 - **响应稳定**: 兼顾高频调用场景下的处理效率和响应速度。 - **并发支持**: 支持批量并发处理，单次最多可分析100个关键词。 - **输入限制**: 单条关键词最多 1,000 字符，总字符数最多 20,000。 - **标准标签**: 返回 `label` 字段，明确区分 `sensitive` 与 `normal`。 - **分类清晰**: 返回 `category` 字段，用于标识具体风险类别。 - **置信度输出**: 返回 `confidence` 字段，范围为0.0到1.0。  ## 响应字段说明  | 字段 | 类型 | 说明 | |------|------|------| | `results` | array | 分析结果对象的数组。 | | `results[].k` | string | 您在请求中提供的原始关键词。 | | `results[].label` | string | 核心判断字段：`sensitive`(敏感)、`normal`(正常)。 | | `results[].category` | string | 风险分类：`safe`(安全)、`threat`(威胁)、`porn`(色情)、`fraud`(欺诈)、`insult`(辱骂)。 | | `results[].confidence` | number | 当前分类的置信度，范围0.0到1.0。 | | `total` | integer | 本次请求成功分析的关键词总数。 |       
pub async fn post_sensitive_word_analyze(configuration: &configuration::Configuration, post_sensitive_word_analyze_request: models::PostSensitiveWordAnalyzeRequest) -> Result<models::PostSensitiveWordAnalyze200Response, Error<PostSensitiveWordAnalyzeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_post_sensitive_word_analyze_request = post_sensitive_word_analyze_request;

    let uri_str = format!("{}/sensitive-word/analyze", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_post_sensitive_word_analyze_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostSensitiveWordAnalyze200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostSensitiveWordAnalyze200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostSensitiveWordAnalyzeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 在你的社区或应用中，需要过滤不适合展示的内容时，这个接口可以帮你快速完成检测。  ## 功能概述  这个接口可以识别文本中的敏感词，并返回是否命中、命中词列表等结果，适合用于评论区、社区、论坛和内容发布场景。  ### 主要特性  - **快速检测**：能够一次处理整段文本中的多个命中内容 - **简繁体支持**：支持简体中文、繁体中文和混合文本检测 - **结果直观**：返回清晰的检测结果，方便直接接入审核流程 - **响应稳定**：适合日常内容审核和批量检查场景  无论是论坛、社交平台还是评论系统，这个接口都能帮你快速构建内容审核功能。
pub async fn post_sensitive_word_quick_check(configuration: &configuration::Configuration, post_sensitive_word_quick_check_request: models::PostSensitiveWordQuickCheckRequest) -> Result<models::PostSensitiveWordQuickCheck200Response, Error<PostSensitiveWordQuickCheckError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_post_sensitive_word_quick_check_request = post_sensitive_word_quick_check_request;

    let uri_str = format!("{}/text/profanitycheck", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_post_sensitive_word_quick_check_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostSensitiveWordQuickCheck200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostSensitiveWordQuickCheck200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostSensitiveWordQuickCheckError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

