/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_avatar_gravatar`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAvatarGravatarError {
    Status400(models::GetAvatarGravatar400Response),
    Status404(models::GetAvatarGravatar404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_image_bing_daily`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetImageBingDailyError {
    Status400(models::GetImageBingDaily400Response),
    Status404(models::GetImageBingDaily404Response),
    Status500(models::GetImageBingDaily500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_image_bing_daily_history`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetImageBingDailyHistoryError {
    Status400(models::GetImageBingDailyHistory400Response),
    Status404(models::GetImageBingDaily404Response),
    Status500(models::GetImageBingDaily500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_image_motou`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetImageMotouError {
    Status400(models::GetImageMotou400Response),
    Status500(models::GetImageMotou500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_image_qrcode`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetImageQrcodeError {
    Status400(models::GetImageQrcode400Response),
    Status500(models::GetImageQrcode500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_image_tobase64`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetImageTobase64Error {
    Status400(models::GetImageTobase64400Response),
    Status502(models::GetImageTobase64502Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_image_compress`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostImageCompressError {
    Status400(models::PostImageCompress400Response),
    Status500(models::PostImageCompress500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_image_decode`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostImageDecodeError {
    Status400(models::PostImageDecode400Response),
    Status413(models::PostImageDecode413Response),
    Status500(models::PostImageDecode500Response),
    Status502(models::PostImageDecode502Response),
    Status503(models::PostImageDecode503Response),
    Status504(models::PostImageDecode504Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_image_frombase64`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostImageFrombase64Error {
    Status400(models::PostImageFrombase64400Response),
    Status500(models::PostImageFrombase64500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_image_motou`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostImageMotouError {
    Status400(models::PostImageMotou400Response),
    Status500(models::PostImageMotou500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_image_nsfw`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostImageNsfwError {
    Status400(models::PostImageNsfw400Response),
    Status413(models::PostImageNsfw413Response),
    Status500(models::PostImageNsfw500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_image_ocr`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostImageOcrError {
    Status400(models::PostImageOcr400Response),
    Status413(models::PostImageOcr413Response),
    Status415(models::PostImageOcr415Response),
    Status502(models::PostImageOcr502Response),
    Status503(models::PostImageOcr503Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_image_speechless`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostImageSpeechlessError {
    Status400(models::PostImageSpeechless400Response),
    Status500(models::PostImageSpeechless500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_image_svg`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostImageSvgError {
    Status400(models::PostImageSvg400Response),
    Status500(models::PostImageSvg500Response),
    UnknownValue(serde_json::Value),
}


/// 提供稳定、易用的头像获取能力，适合在网页或应用中直接展示头像。
pub async fn get_avatar_gravatar(configuration: &configuration::Configuration, email: Option<&str>, hash: Option<&str>, s: Option<i32>, d: Option<&str>, r: Option<&str>) -> Result<reqwest::Response, Error<GetAvatarGravatarError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_email = email;
    let p_query_hash = hash;
    let p_query_s = s;
    let p_query_d = d;
    let p_query_r = r;

    let uri_str = format!("{}/avatar/gravatar", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_email {
        req_builder = req_builder.query(&[("email", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_hash {
        req_builder = req_builder.query(&[("hash", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_s {
        req_builder = req_builder.query(&[("s", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_d {
        req_builder = req_builder.query(&[("d", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_r {
        req_builder = req_builder.query(&[("r", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAvatarGravatarError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 这个接口可以获取最新或指定日期的必应壁纸。默认直接返回图片，也可以传 `format=json` 获取元数据，或者传 `format=redirect` 直接跳转到最终图片地址。  ## 功能概述 - 不传参数时，默认返回当天壁纸图片二进制 - 可以传 `date` 查询指定日期的壁纸 - 可以传 `resolution` 选择 `4k` 或 `1080` - 可以传 `format` 控制返回图片、JSON 或 302 跳转 - 当传 `format=json` 时，返回的是扁平 JSON 对象，里面会包含标题、副标题、说明文案、版权信息、问答信息和图片地址等字段  ## 参数说明 `resolution` 默认是 `4k`。 `format` 默认是 `image`。
pub async fn get_image_bing_daily(configuration: &configuration::Configuration, date: Option<&str>, resolution: Option<&str>, format: Option<&str>) -> Result<reqwest::Response, Error<GetImageBingDailyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_date = date;
    let p_query_resolution = resolution;
    let p_query_format = format;

    let uri_str = format!("{}/image/bing-daily", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_resolution {
        req_builder = req_builder.query(&[("resolution", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_format {
        req_builder = req_builder.query(&[("format", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<GetImageBingDailyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 这个接口用于查询必应壁纸历史列表，也可以按日期精确查询某一天。默认按时间倒序返回 JSON。  ## 功能概述 - 可以传 `date` 精确查询某一天，命中后只返回 1 条数据 - 不传 `date` 时，按时间倒序分页返回历史列表 - 可以传 `resolution` 让 `image_url` 直接对应 `4k` 或 `1080` - 可以传 `page` 和 `page_size` 控制分页 - 每条记录都是扁平 JSON 对象，里面会包含标题、副标题、说明文案、版权信息、问答信息和图片地址等字段  ## 参数说明 `resolution` 默认是 `4k`。 `page` 默认是 `1`，`page_size` 默认是 `30`，最大是 `100`。 当传了 `date` 以后，`page` 和 `page_size` 不生效。
pub async fn get_image_bing_daily_history(configuration: &configuration::Configuration, date: Option<&str>, resolution: Option<&str>, page: Option<i32>, page_size: Option<i32>) -> Result<models::GetImageBingDailyHistory200Response, Error<GetImageBingDailyHistoryError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_date = date;
    let p_query_resolution = resolution;
    let p_query_page = page;
    let p_query_page_size = page_size;

    let uri_str = format!("{}/image/bing-daily/history", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_resolution {
        req_builder = req_builder.query(&[("resolution", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetImageBingDailyHistory200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetImageBingDailyHistory200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetImageBingDailyHistoryError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 想在线rua一下好友的头像吗？这个趣味接口可以满足你。  ## 功能概述 此接口通过GET方法，专门用于通过QQ号生成摸摸头GIF。你只需要提供一个QQ号码，我们就会自动获取其公开头像，并制作成一个可爱的动图。  ## 使用须知 - **响应格式**：接口成功时直接返回 `image/gif` 格式的二进制数据。 - **背景颜色**：你可以通过 `bg_color` 参数来控制GIF的背景。使用 `transparent` 选项可以让它更好地融入各种聊天背景中。
pub async fn get_image_motou(configuration: &configuration::Configuration, qq: &str, bg_color: Option<&str>) -> Result<reqwest::Response, Error<GetImageMotouError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_qq = qq;
    let p_query_bg_color = bg_color;

    let uri_str = format!("{}/image/motou", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("qq", &p_query_qq.to_string())]);
    if let Some(ref param_value) = p_query_bg_color {
        req_builder = req_builder.query(&[("bg_color", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<GetImageMotouError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 无论是网址、文本还是联系方式，通通可以变成一个二维码！这是一个非常灵活的二维码生成工具。  ## 功能概述 你提供一段文本内容，我们为你生成对应的二维码图片。你可以自定义尺寸、前景色、背景色，还支持透明背景，并选择不同的返回格式以适应不同场景。
pub async fn get_image_qrcode(configuration: &configuration::Configuration, text: &str, size: Option<i32>, format: Option<&str>, transparent: Option<bool>, fgcolor: Option<&str>, bgcolor: Option<&str>) -> Result<reqwest::Response, Error<GetImageQrcodeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_text = text;
    let p_query_size = size;
    let p_query_format = format;
    let p_query_transparent = transparent;
    let p_query_fgcolor = fgcolor;
    let p_query_bgcolor = bgcolor;

    let uri_str = format!("{}/image/qrcode", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("text", &p_query_text.to_string())]);
    if let Some(ref param_value) = p_query_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_format {
        req_builder = req_builder.query(&[("format", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_transparent {
        req_builder = req_builder.query(&[("transparent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_fgcolor {
        req_builder = req_builder.query(&[("fgcolor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_bgcolor {
        req_builder = req_builder.query(&[("bgcolor", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<GetImageQrcodeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 看到一张网上的图片，想把它转换成 Base64 编码以便嵌入到你的 HTML 或 CSS 中？用这个接口就对了。  ## 功能概述 你提供一个公开可访问的图片 URL，我们帮你把它下载下来，并转换成包含 MIME 类型的 Base64 Data URI 字符串返回给你。
pub async fn get_image_tobase64(configuration: &configuration::Configuration, url: &str) -> Result<models::GetImageTobase64200Response, Error<GetImageTobase64Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_url = url;

    let uri_str = format!("{}/image/tobase64", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("url", &p_query_url.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetImageTobase64200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetImageTobase64200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetImageTobase64Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 还在为图片体积和加载速度发愁吗？体验一下我们强大的**无损压缩服务**，它能在几乎不牺牲任何肉眼可感知的画质的前提下，将图片体积压缩到极致。  ## 功能概述 你只需要上传一张常见的图片（如 PNG, JPG），选择一个压缩等级，就能获得一个体积小到惊人的压缩文件。这对于需要大量展示高清图片的网站、App 或小程序来说，是优化用户体验、节省带宽和存储成本的利器。  ## 使用须知 > [!TIP] > 图片越大或压缩等级越高，处理时间可能越长，请您耐心等待。  > [!WARNING] > **处理时间提醒** > 在访问量较高时，处理时间可能进一步延长。如果您的业务对返回时间比较敏感，建议预留充足的处理时间。  ### 请求与响应格式 - 请求必须使用 `multipart/form-data` 格式上传文件。 - 成功响应将直接返回压缩后的文件二进制流 (`image/_*`)，并附带 `Content-Disposition` 头，建议客户端根据此头信息保存文件。  ## 参数详解 ### `level` (压缩等级) 这是一个从 `1` 到 `5` 的整数，它决定了压缩的强度和策略，数字越小，压缩率越高。所有等级都经过精心调校，以在最大化压缩率的同时保证出色的视觉质量。 - `1`: **极限压缩** (推荐，体积最小，画质优异) - `2`: **高效压缩** - `3`: **智能均衡** (默认选项) - `4`: **画质优先** - `5`: **专业保真** (压缩率稍低，保留最多图像信息)  ## 错误处理指南 - **400 Bad Request**: 通常因为没有上传文件，或者 `level` 参数不在 1-5 的范围内。 - **500 Internal Server Error**: 如果在压缩过程中服务器发生内部错误，会返回此状态码。
pub async fn post_image_compress(configuration: &configuration::Configuration, file: std::path::PathBuf, level: Option<i32>, format: Option<&str>) -> Result<reqwest::Response, Error<PostImageCompressError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_file = file;
    let p_query_level = level;
    let p_query_format = format;

    let uri_str = format!("{}/image/compress", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query_level {
        req_builder = req_builder.query(&[("level", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_format {
        req_builder = req_builder.query(&[("format", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form = reqwest::multipart::Form::new();
    // TODO: support file upload for 'file' parameter
    req_builder = req_builder.multipart(multipart_form);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<PostImageCompressError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 在 RAM 和 Flash 极其有限的设备上解码图片是一项繁重的任务。这个接口专为 IoT 和嵌入式开发设计，将复杂的图像解码和缩放操作转移到云端，直接输出适用于单片机屏幕的二进制像素流。  ## 功能概述 此接口提供了灵活的云端图像预处理能力，帮助硬件开发者跳过繁琐的图像处理逻辑： - **直接推流渲染**：如果选择输出纯像素流（如 RGB565），单片机收到网络数据后无需解析文件头，可直接将其写入显存，实现极低内存占用的边下边播。 - **完美适配屏幕**：无需在设备端编写裁剪或补边代码。只需传入目标屏幕的物理分辨率，接口会自动完成等比缩放、居中补色或铺满裁剪，确保最终显示画面不变形。 - **精准内存分配**：在动态缩放图片的场景下，服务端会在 HTTP 响应头中提前注入 `X-Image-Width` 和 `X-Image-Height`，方便设备在读取真实的二进制数据前进行准确的内存分配。  ## 使用须知 - **请求格式**：无论是上传本地文件还是传递图片链接，请求体都必须使用 `multipart/form-data` 编码格式。 - **网络资源获取**：当您选择传递图片链接时，服务端会自动尝试获取该资源。请确保您提供的图片链接是公网直接可访问的，且不需要任何形式的登录鉴权。
pub async fn post_image_decode(configuration: &configuration::Configuration, width: Option<i32>, height: Option<i32>, max_width: Option<i32>, max_height: Option<i32>, format: Option<&str>, color_mode: Option<&str>, fit: Option<&str>, background: Option<&str>, file: Option<std::path::PathBuf>, url: Option<&str>) -> Result<reqwest::Response, Error<PostImageDecodeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_width = width;
    let p_query_height = height;
    let p_query_max_width = max_width;
    let p_query_max_height = max_height;
    let p_query_format = format;
    let p_query_color_mode = color_mode;
    let p_query_fit = fit;
    let p_query_background = background;
    let p_form_file = file;
    let p_form_url = url;

    let uri_str = format!("{}/image/decode", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query_width {
        req_builder = req_builder.query(&[("width", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_height {
        req_builder = req_builder.query(&[("height", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_max_width {
        req_builder = req_builder.query(&[("max_width", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_max_height {
        req_builder = req_builder.query(&[("max_height", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_format {
        req_builder = req_builder.query(&[("format", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_color_mode {
        req_builder = req_builder.query(&[("color_mode", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_fit {
        req_builder = req_builder.query(&[("fit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_background {
        req_builder = req_builder.query(&[("background", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form = reqwest::multipart::Form::new();
    // TODO: support file upload for 'file' parameter
    if let Some(param_value) = p_form_url {
        multipart_form = multipart_form.text("url", param_value.to_string());
    }
    req_builder = req_builder.multipart(multipart_form);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<PostImageDecodeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 当你需要在前端处理完图片（比如裁剪、加滤镜后），不通过传统表单，而是直接上传图片的场景，这个接口就派上用场了。  ## 功能概述 你只需要将图片的 Base64 编码字符串发送过来，我们就会把它解码、保存为图片文件，并返回一个可供访问的公开 URL。  ## 使用须知  > [!IMPORTANT] > **关于 `imageData` 格式** > 你发送的 `imageData` 字符串必须是完整的 Base64 Data URI 格式，它需要包含 MIME 类型信息，例如 `data:image/png;base64,iVBORw0KGgo...`。缺少 `data:image/...;base64,` 前缀将导致解码失败。
pub async fn post_image_frombase64(configuration: &configuration::Configuration, post_image_frombase64_request: models::PostImageFrombase64Request) -> Result<models::PostImageFrombase64200Response, Error<PostImageFrombase64Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_post_image_frombase64_request = post_image_frombase64_request;

    let uri_str = format!("{}/image/frombase64", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_post_image_frombase64_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostImageFrombase64200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostImageFrombase64200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostImageFrombase64Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 除了使用QQ头像，你还可以通过上传自己的图片或提供图片URL来制作独一无二的摸摸头GIF。  ## 功能概述 此接口通过POST方法，支持两种方式生成GIF： 1.  **图片URL**：在表单中提供 `image_url` 字段。 2.  **上传图片**：在表单中上传 `file` 文件。  ## 使用须知 - **响应格式**：接口成功时直接返回 `image/gif` 格式的二进制数据。 - **参数优先级**：如果同时提供了 `image_url` 和上传的 `file` 文件，系统将 **优先使用 `image_url`**。 - **背景颜色**：同样支持 `bg_color` 表单字段来控制GIF背景。
pub async fn post_image_motou(configuration: &configuration::Configuration, image_url: Option<&str>, file: Option<std::path::PathBuf>, bg_color: Option<&str>) -> Result<reqwest::Response, Error<PostImageMotouError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_image_url = image_url;
    let p_form_file = file;
    let p_form_bg_color = bg_color;

    let uri_str = format!("{}/image/motou", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form = reqwest::multipart::Form::new();
    if let Some(param_value) = p_form_image_url {
        multipart_form = multipart_form.text("image_url", param_value.to_string());
    }
    // TODO: support file upload for 'file' parameter
    if let Some(param_value) = p_form_bg_color {
        multipart_form = multipart_form.text("bg_color", param_value.to_string());
    }
    req_builder = req_builder.multipart(multipart_form);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<PostImageMotouError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 这是一个图片内容审核接口，自动识别图片中的违规内容并返回处理建议。  ## 功能概述 上传图片文件或提供图片URL，接口会自动分析图片内容，返回是否违规、风险等级和处理建议。适合对接到用户上传流程中，实现自动化内容审核。  ## 返回字段说明 - **is_nsfw**: 是否判定为违规内容，`true` 表示违规，`false` 表示正常 - **nsfw_score**: 违规内容置信度，0-1 之间，越高表示越可能违规 - **normal_score**: 正常内容置信度，0-1 之间，与 nsfw_score 互补 - **suggestion**: 处理建议   - `pass`: 内容正常，可以直接放行   - `review`: 存在风险，建议转人工复核   - `block`: 高风险内容，建议直接拦截 - **risk_level**: 风险等级   - `low`: 低风险   - `medium`: 中风险   - `high`: 高风险 - **label**: 内容标签，`nsfw` 或 `normal` - **confidence**: 模型对当前判断的整体置信度 - **inference_time_ms**: 模型推理耗时，单位毫秒
pub async fn post_image_nsfw(configuration: &configuration::Configuration, file: Option<std::path::PathBuf>, url: Option<&str>) -> Result<models::PostImageNsfw200Response, Error<PostImageNsfwError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_file = file;
    let p_form_url = url;

    let uri_str = format!("{}/image/nsfw", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form = reqwest::multipart::Form::new();
    // TODO: support file upload for 'file' parameter
    if let Some(param_value) = p_form_url {
        multipart_form = multipart_form.text("url", param_value.to_string());
    }
    req_builder = req_builder.multipart(multipart_form);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostImageNsfw200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostImageNsfw200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostImageNsfwError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 无论您是需要实现票据的自动化录入，还是在网页前端对图片上的文字进行坐标框选，这个高精度的 OCR 接口都能为您提供强大的基础能力。  ## 功能概述 > [!IMPORTANT] > 如果您只关心图片上写了什么（例如截图取字或内容安全审核），强烈建议将 `need_location` 设置为 `false`。这会大幅精简返回的 JSON 数据体积，提升网络传输与系统解析效率。  除了常规的图片转文字，这个接口还针对实际开发场景做了一些实用设计： - **前端文字高亮与结构化分析**：默认返回每一段文字的矩形坐标和四个顶点坐标。这非常适合使用 Canvas 在原图上画框高亮，或者在后端根据相对位置提取票据中的键值对信息。 - **复杂拍摄环境下的抗畸变**：针对手机拍摄导致的旋转或倾斜，可以开启 `enable_cls=true`。服务端在识别前会自动进行方向预校正，显著提升识别准确率。 - **灵活的输入与请求要求**：接口支持 `file`、`url` 或 `image_base64` 三种方式输入。请确保请求格式为 `multipart/form-data`，且图片链接在公网可直接访问。
pub async fn post_image_ocr(configuration: &configuration::Configuration, file: Option<std::path::PathBuf>, url: Option<&str>, image_base64: Option<&str>, image_name: Option<&str>, need_location: Option<&str>, return_markdown: Option<&str>, enable_cls: Option<&str>) -> Result<models::PostImageOcr200Response, Error<PostImageOcrError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_file = file;
    let p_form_url = url;
    let p_form_image_base64 = image_base64;
    let p_form_image_name = image_name;
    let p_form_need_location = need_location;
    let p_form_return_markdown = return_markdown;
    let p_form_enable_cls = enable_cls;

    let uri_str = format!("{}/image/ocr", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form = reqwest::multipart::Form::new();
    // TODO: support file upload for 'file' parameter
    if let Some(param_value) = p_form_url {
        multipart_form = multipart_form.text("url", param_value.to_string());
    }
    if let Some(param_value) = p_form_image_base64 {
        multipart_form = multipart_form.text("image_base64", param_value.to_string());
    }
    if let Some(param_value) = p_form_image_name {
        multipart_form = multipart_form.text("image_name", param_value.to_string());
    }
    if let Some(param_value) = p_form_need_location {
        multipart_form = multipart_form.text("need_location", param_value.to_string());
    }
    if let Some(param_value) = p_form_return_markdown {
        multipart_form = multipart_form.text("return_markdown", param_value.to_string());
    }
    if let Some(param_value) = p_form_enable_cls {
        multipart_form = multipart_form.text("enable_cls", param_value.to_string());
    }
    req_builder = req_builder.multipart(multipart_form);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostImageOcr200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostImageOcr200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostImageOcrError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 你们怎么不说话了？是不是都在偷偷玩Uapi，求求你们不要玩Uapi了  ## 使用须知 - **响应格式**：接口成功时直接返回 `image/png` 格式的二进制数据。 - **文字内容**：至少需要提供 `top_text`（上方文字）或 `bottom_text`（下方文字）之一。 - **梗图逻辑**：上方描述某个行为，下方通常以「们」开头表示劝阻，形成戏谑的对比效果。
pub async fn post_image_speechless(configuration: &configuration::Configuration, post_image_speechless_request: models::PostImageSpeechlessRequest) -> Result<reqwest::Response, Error<PostImageSpeechlessError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_post_image_speechless_request = post_image_speechless_request;

    let uri_str = format!("{}/image/speechless", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_post_image_speechless_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<PostImageSpeechlessError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// 需要将灵活的 SVG 矢量图形转换为常见的光栅图像格式吗？这个接口可以帮你轻松实现。  ## 功能概述 上传一个 SVG 文件，并指定目标格式（如 PNG、JPEG 等），接口将返回转换后的图像。你还可以调整输出图像的尺寸和（对于JPEG）压缩质量，以满足不同场景的需求。
pub async fn post_image_svg(configuration: &configuration::Configuration, format: Option<&str>, width: Option<i32>, height: Option<i32>, quality: Option<i32>, file: Option<std::path::PathBuf>) -> Result<reqwest::Response, Error<PostImageSvgError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_format = format;
    let p_query_width = width;
    let p_query_height = height;
    let p_query_quality = quality;
    let p_form_file = file;

    let uri_str = format!("{}/image/svg", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query_format {
        req_builder = req_builder.query(&[("format", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_width {
        req_builder = req_builder.query(&[("width", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_height {
        req_builder = req_builder.query(&[("height", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_quality {
        req_builder = req_builder.query(&[("quality", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form = reqwest::multipart::Form::new();
    // TODO: support file upload for 'file' parameter
    req_builder = req_builder.multipart(multipart_form);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<PostImageSvgError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

